server:
  port: 8767

spring:
  application:
    name: feign-hystrix

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

# 开始hystrix服务
feign:
  hystrix:
    enabled: true